var Contig_ref = {
  "KPC33_p1": {
    "accession": "KPC33_p1",
    "qlen": 67418,
    "definition": "KPC33_p1 KPC-33 IncN plasmid, 26ET500373, hybrid assembly contig 3",
    "organism": "",
    "orfs": [
      {
        "id": 0,
        "sidx": 0,
        "eidx": 720,
        "strand": 1,
        "type": "other",
        "dbname": "UniProt/SwissProt",
        "refprotien": "sp|P18351|YPC1_ECOLX",
        "idty": 99.582,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "sp|P18351|YPC1_ECOLX Uncharacterized 27.6 kDa protein OS=Escherichia coli OX=562 PE=3 SV=2",
        "linkout": null
      },
      {
        "id": 1,
        "sidx": 764,
        "eidx": 1928,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 2,
        "sidx": 2044,
        "eidx": 2239,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 3,
        "sidx": 2252,
        "eidx": 2390,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 4,
        "sidx": 2680,
        "eidx": 4156,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 5,
        "sidx": 4475,
        "eidx": 5177,
        "strand": -1,
        "type": "other",
        "dbname": "UniProt/SwissProt",
        "refprotien": "sp|P18128|YPC2_ECOLX",
        "idty": 73.262,
        "cov": 80.25751072961373,
        "gap": 0,
        "mismatch": 0,
        "dscr": "sp|P18128|YPC2_ECOLX Uncharacterized 26.4 kDa protein OS=Escherichia coli OX=562 PE=4 SV=3",
        "linkout": null
      },
      {
        "id": 6,
        "sidx": 5199,
        "eidx": 5442,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 7,
        "sidx": 5395,
        "eidx": 5548,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 8,
        "sidx": 5544,
        "eidx": 6114,
        "strand": -1,
        "type": "other",
        "dbname": "UniProt/SwissProt",
        "refprotien": "sp|P18957|UVP1_ECOLX",
        "idty": 89.894,
        "cov": 99.47089947089947,
        "gap": 0,
        "mismatch": 0,
        "dscr": "sp|P18957|UVP1_ECOLX Protein uvp1 OS=Escherichia coli OX=562 GN=uvp1 PE=3 SV=1",
        "linkout": null
      },
      {
        "id": 9,
        "sidx": 6353,
        "eidx": 7568,
        "strand": 1,
        "type": "other",
        "dbname": "UniProt/SwissProt",
        "refprotien": "sp|P14633|T2E2_ECOLX",
        "idty": 97.277,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "sp|P14633|T2E2_ECOLX Type II restriction enzyme EcoRII OS=Escherichia coli OX=562 GN=ecoRIIR PE=1 SV=2",
        "linkout": null
      },
      {
        "id": 10,
        "sidx": 7601,
        "eidx": 9035,
        "strand": -1,
        "type": "other",
        "dbname": "UniProt/SwissProt",
        "refprotien": "sp|P05101|MTE2_ECOLX",
        "idty": 99.79,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "sp|P05101|MTE2_ECOLX Type II methyltransferase M.EcoRII OS=Escherichia coli OX=562 GN=ecoRIIM PE=1 SV=1",
        "linkout": null
      },
      {
        "id": 11,
        "sidx": 9109,
        "eidx": 9307,
        "strand": -1,
        "type": "isel",
        "dbname": "ISFinder",
        "refprotien": "IS1X1_IS1_unknown",
        "idty": 87.097,
        "cov": 95.38461538461539,
        "gap": 0,
        "mismatch": 0,
        "dscr": "IS1X1_IS1_unknown",
        "linkout": null
      },
      {
        "id": 12,
        "sidx": 9416,
        "eidx": 9623,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 13,
        "sidx": 9627,
        "eidx": 9882,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 14,
        "sidx": 10064,
        "eidx": 11033,
        "strand": 1,
        "type": "isel",
        "dbname": "ISFinder",
        "refprotien": "IS903B_IS5_IS903",
        "idty": 97.205,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "IS903B_IS5_IS903",
        "linkout": null
      },
      {
        "id": 15,
        "sidx": 11074,
        "eidx": 11335,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 16,
        "sidx": 11390,
        "eidx": 11624,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 17,
        "sidx": 11737,
        "eidx": 12052,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 18,
        "sidx": 12048,
        "eidx": 12393,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 19,
        "sidx": 12408,
        "eidx": 12780,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 20,
        "sidx": 12957,
        "eidx": 13560,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 21,
        "sidx": 13568,
        "eidx": 13850,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 22,
        "sidx": 13859,
        "eidx": 14153,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 23,
        "sidx": 14203,
        "eidx": 14521,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 24,
        "sidx": 14520,
        "eidx": 17121,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 25,
        "sidx": 17138,
        "eidx": 17852,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 26,
        "sidx": 17859,
        "eidx": 18087,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 27,
        "sidx": 18102,
        "eidx": 19143,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 28,
        "sidx": 19361,
        "eidx": 20060,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 29,
        "sidx": 20070,
        "eidx": 20955,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 30,
        "sidx": 20954,
        "eidx": 22115,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 31,
        "sidx": 22156,
        "eidx": 23152,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 32,
        "sidx": 23151,
        "eidx": 23331,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 33,
        "sidx": 23607,
        "eidx": 24927,
        "strand": 1,
        "type": "isel",
        "dbname": "ISFinder",
        "refprotien": "ISKpn6_IS1182_unknown",
        "idty": 100.0,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "ISKpn6_IS1182_unknown",
        "linkout": null
      },
      {
        "id": 34,
        "sidx": 25176,
        "eidx": 26058,
        "strand": -1,
        "type": "args",
        "dbname": "CARD",
        "refprotien": "gb|AUD37084.1|ARO:3005365|KPC-33",
        "idty": 100.0,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "KPC-33",
        "linkout": null
      },
      {
        "id": 35,
        "sidx": 26316,
        "eidx": 27177,
        "strand": -1,
        "type": "args",
        "dbname": "CARD",
        "refprotien": "gb|CAD09800.1|ARO:3000873|TEM-1",
        "idty": 100.0,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "TEM-1",
        "linkout": null
      },
      {
        "id": 36,
        "sidx": 27997,
        "eidx": 29365,
        "strand": -1,
        "type": "isel",
        "dbname": "ISFinder",
        "refprotien": "ISCfr1_IS1182_unknown",
        "idty": 100.0,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "ISCfr1_IS1182_unknown",
        "linkout": null
      },
      {
        "id": 37,
        "sidx": 29482,
        "eidx": 30640,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 38,
        "sidx": 30669,
        "eidx": 30915,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 39,
        "sidx": 31593,
        "eidx": 32136,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 40,
        "sidx": 32148,
        "eidx": 33009,
        "strand": -1,
        "type": "args",
        "dbname": "CARD",
        "refprotien": "gb|ABS70977.1|ARO:3004623|AAC(3)-IId",
        "idty": 100.0,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "AAC(3)-IId",
        "linkout": null
      },
      {
        "id": 41,
        "sidx": 33241,
        "eidx": 33946,
        "strand": 1,
        "type": "isel",
        "dbname": "ISFinder",
        "refprotien": "IS26_IS6_unknown",
        "idty": 99.573,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "IS26_IS6_unknown",
        "linkout": null
      },
      {
        "id": 42,
        "sidx": 34220,
        "eidx": 35069,
        "strand": -1,
        "type": "integrase",
        "dbname": "UniProt/SwissProt",
        "refprotien": "sp|P62592|INT2_SALTI",
        "idty": 99.645,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "sp|P62592|INT2_SALTI Integrase/recombinase OS=Salmonella typhi OX=90370 GN=int PE=3 SV=1",
        "linkout": null
      },
      {
        "id": 43,
        "sidx": 35263,
        "eidx": 35863,
        "strand": 1,
        "type": "args",
        "dbname": "CARD",
        "refprotien": "gb|AAC46343.1|ARO:3002581|AAC(6')-Ib10",
        "idty": 97.98,
        "cov": 99.49748743718592,
        "gap": 0,
        "mismatch": 0,
        "dscr": "AAC(6')-Ib10",
        "linkout": null
      },
      {
        "id": 44,
        "sidx": 35948,
        "eidx": 36824,
        "strand": 1,
        "type": "args",
        "dbname": "CARD",
        "refprotien": "gb|AFB82783.1|ARO:3001396|OXA-1",
        "idty": 100.0,
        "cov": 94.84536082474227,
        "gap": 0,
        "mismatch": 0,
        "dscr": "OXA-1",
        "linkout": null
      },
      {
        "id": 45,
        "sidx": 36961,
        "eidx": 37594,
        "strand": 1,
        "type": "args",
        "dbname": "CARD",
        "refprotien": "gb|AFQ93498.1|ARO:3002676|catB3",
        "idty": 100.0,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "catB3",
        "linkout": null
      },
      {
        "id": 46,
        "sidx": 37678,
        "eidx": 38131,
        "strand": 1,
        "type": "args",
        "dbname": "CARD",
        "refprotien": "gb|ACD56151.1|ARO:3002848|arr-3",
        "idty": 100.0,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "arr-3",
        "linkout": null
      },
      {
        "id": 47,
        "sidx": 38694,
        "eidx": 39534,
        "strand": 1,
        "type": "args",
        "dbname": "CARD",
        "refprotien": "gb|AEJ33969.1|ARO:3000410|sul1",
        "idty": 100.0,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "sul1",
        "linkout": null
      },
      {
        "id": 48,
        "sidx": 39938,
        "eidx": 41480,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 49,
        "sidx": 41745,
        "eidx": 42246,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 50,
        "sidx": 42245,
        "eidx": 42815,
        "strand": 1,
        "type": "args",
        "dbname": "CARD",
        "refprotien": "gb|CAC81324.1|ARO:3003015|dfrA19",
        "idty": 99.471,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "dfrA19",
        "linkout": null
      },
      {
        "id": 51,
        "sidx": 42762,
        "eidx": 43431,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 52,
        "sidx": 43417,
        "eidx": 44431,
        "strand": -1,
        "type": "integrase",
        "dbname": "UniProt/SwissProt",
        "refprotien": "sp|P62592|INT2_SALTI",
        "idty": 100.0,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "sp|P62592|INT2_SALTI Integrase/recombinase OS=Salmonella typhi OX=90370 GN=int PE=3 SV=1",
        "linkout": null
      },
      {
        "id": 53,
        "sidx": 44462,
        "eidx": 45392,
        "strand": 1,
        "type": "args",
        "dbname": "CARD",
        "refprotien": "gb|ABK33456.1|ARO:3002639|APH(3'')-Ib",
        "idty": 99.251,
        "cov": 86.40776699029126,
        "gap": 0,
        "mismatch": 0,
        "dscr": "APH(3'')-Ib",
        "linkout": null
      },
      {
        "id": 54,
        "sidx": 45391,
        "eidx": 46228,
        "strand": 1,
        "type": "args",
        "dbname": "CARD",
        "refprotien": "gb|AAC23556.1|ARO:3002660|APH(6)-Id",
        "idty": 99.64,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "APH(6)-Id",
        "linkout": null
      },
      {
        "id": 55,
        "sidx": 46372,
        "eidx": 47200,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 56,
        "sidx": 47214,
        "eidx": 47556,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 57,
        "sidx": 47895,
        "eidx": 48600,
        "strand": -1,
        "type": "isel",
        "dbname": "ISFinder",
        "refprotien": "IS26_IS6_unknown",
        "idty": 99.145,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "IS26_IS6_unknown",
        "linkout": null
      },
      {
        "id": 58,
        "sidx": 48611,
        "eidx": 48947,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 59,
        "sidx": 48936,
        "eidx": 49338,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 60,
        "sidx": 49334,
        "eidx": 49625,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 61,
        "sidx": 49688,
        "eidx": 50087,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 62,
        "sidx": 50086,
        "eidx": 53323,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 63,
        "sidx": 53322,
        "eidx": 54852,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 64,
        "sidx": 54853,
        "eidx": 55270,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 65,
        "sidx": 55858,
        "eidx": 56245,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 66,
        "sidx": 56253,
        "eidx": 56970,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 67,
        "sidx": 56971,
        "eidx": 57340,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 68,
        "sidx": 57540,
        "eidx": 57885,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 69,
        "sidx": 58346,
        "eidx": 58526,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 70,
        "sidx": 58528,
        "eidx": 58948,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 71,
        "sidx": 59292,
        "eidx": 59400,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 72,
        "sidx": 59884,
        "eidx": 60217,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 73,
        "sidx": 60347,
        "eidx": 60677,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 74,
        "sidx": 60778,
        "eidx": 61138,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 75,
        "sidx": 61134,
        "eidx": 61431,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 76,
        "sidx": 61543,
        "eidx": 62089,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 77,
        "sidx": 62088,
        "eidx": 62244,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 78,
        "sidx": 62315,
        "eidx": 62555,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 79,
        "sidx": 62564,
        "eidx": 62900,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 80,
        "sidx": 63026,
        "eidx": 63452,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 81,
        "sidx": 64025,
        "eidx": 64208,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 82,
        "sidx": 64295,
        "eidx": 65561,
        "strand": 1,
        "type": "other",
        "dbname": "UniProt/SwissProt",
        "refprotien": "sp|P14303|MUCB_SALTM",
        "idty": 99.762,
        "cov": 100.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "sp|P14303|MUCB_SALTM Protein MucB OS=Salmonella typhimurium OX=90371 GN=mucB PE=3 SV=1",
        "linkout": null
      },
      {
        "id": 83,
        "sidx": 65675,
        "eidx": 66503,
        "strand": 1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      },
      {
        "id": 84,
        "sidx": 66517,
        "eidx": 66859,
        "strand": -1,
        "type": "hypothetical",
        "dbname": "",
        "refprotien": "",
        "idty": 0.0,
        "cov": 0.0,
        "gap": 0,
        "mismatch": 0,
        "dscr": "hypothetical protein",
        "linkout": null
      }
    ],
    "annotations": []
  }
};
